### ISSUE TITLE
Fails to install because of dependency to old coffee-script.

### ISSUE THREAD

**Issue by ChrisDawe** [cypress-io/cypress-browserify-preprocessor#21]
When trying to install this, it fails. It depends on cjsxify https://www.npmjs.com/package/cjsxify
which depends on coffee-script https://www.npmjs.com/package/coffee-script, which has been deprecated.
New npm package is coffeescript without the hyphen.

**Comment by chrisbreiding** [comment]
We'll update the dependency, but it should just be a deprecation warning and not fail the installation.

**Comment by ChrisDawe** [comment]
Thanks for the quick response. I figured out that the reason it fails is it is trying to install coffee-script 1.12.8, but the last version was 1.12.7. Trying to do "npm i coffee-script" also fails trying to load 1.12.8, so it seems like maybe an npm issue where it has latest wrong?
Doing "npm i coffee-script@1.12.7" works, and allows cypress-browserify-preprocessor to install correctly.

**Comment by chrisbreiding** [comment]
There's definitely something weird going on with that. I wasn't able to reproduce it though. 

In any case, I just released [v2.0.0](https://github.com/cypress-io/cypress-browserify-preprocessor/releases/tag/v2.0.0). Using that should solve the problem your encountering. It uses `coffeeify` instead of `cjsxify` and uses the `coffeescript` (not `coffee-script`) package, locked to 1.12.7. 

Since `csxify` controls the version of `coffeescript`, I would have had to fork it to update the version of `coffeescript` it uses. Also, it looks to be unmaintained as it hasn't been updated in 4 years. This removes `cjsx` support, which is why this is a new major version.
