### ISSUE TITLE
Plugin is obsolete?

### ISSUE THREAD

**Issue by bvanderneut** [cypress-io/cypress-browserify-preprocessor#41]
I guess this plugin is now obsolete with the latest version 4.4.0 of Cypress right?

**Comment by chrisbreiding** [comment]
This plugin's primary purposes is to allow customizing your preprocessor to your needs, so that purpose still stands. Cypress now includes TypeScript support by default, but that's only one use-case.

More than that, this plugin is [what Cypress itself uses](https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/plugins/preprocessor.coffee#L43) for its default handling of file preprocessing, so it's certainly necessary for that reason alone 😄
